version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      PORT: 8080
    restart: always
